- packages/puppeteer-extra-plugin/package.json
- packages/puppeteer-extra/package.json
> Add peer dependencies

- packages/puppeteer-extra-plugin/index.js
- packages/puppeteer-extra-plugin/package.json
- packages/puppeteer-extra/package.json
- yarn.lock
> Fix compat, deprecate browser.onClose

- packages/puppeteer-extra/index.js
> fix(puppeteer-extra): Fix incognito context  (fixes #36)

- .travis.yml
- packages/puppeteer-extra-plugin-adblocker/package.json
- packages/puppeteer-extra-plugin-adblocker/src/ambient.d.ts
- packages/puppeteer-extra-plugin-devtools/package.json
- packages/puppeteer-extra-plugin-recaptcha/package.json
- packages/puppeteer-extra-plugin-recaptcha/src/ambient.d.ts
- packages/puppeteer-extra-plugin/package.json
- packages/puppeteer-extra-plugin/src/ambient.d.ts
- packages/puppeteer-extra/package.json
- packages/puppeteer-extra/src/ambient.d.ts
- packages/puppeteer-extra/test/events.js
- yarn.lock
> Fix CI issues

- packages/puppeteer-extra-plugin-flash/index.js
This fixes issue https://github.com/berstend/puppeteer-extra/issues/131 and at the same time cleans up the preference code a bit. Please test carefully, but works fine on my tests.
Credit to this post by @cztomczak which put me in the right direction: https://magpcss.org/ceforum/viewtopic.php?p=43396&sid=fb0574fa7afface5976d913e330dba0b#p43396
> Fix Flash plugin on Chrome 76+, fix #131

- packages/puppeteer-extra-plugin-repl/index.d.ts
- packages/puppeteer-extra-plugin-repl/package.json
This adds definition file to be shipped with the package itself.
Useful for TS usage, when JS code is checked for errors with TSC.
Thanks!
> feat(plugin-repl): add definition file

- packages/puppeteer-extra-plugin/package.json
- packages/puppeteer-extra-plugin/rollup.config.ts
> Remove unused default import for camelCase

- packages/extract-stealth-evasions/.gitignore
- packages/extract-stealth-evasions/index.js
- packages/extract-stealth-evasions/readme.md
> Add ability to disable minify in stealth extract

- packages/puppeteer-extra-plugin-adblocker/package.json
- packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.js
- packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.test.js
> fix(plugin-stealth): Fix leaking stack traces in createElement

- packages/puppeteer-extra-plugin-recaptcha/readme.md
- packages/puppeteer-extra-plugin-recaptcha/src/content.ts
- packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha-api.ts
- packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha.ts
- packages/puppeteer-extra-plugin-recaptcha/src/types.ts
This PR:
- adds support for the new reCAPTCHA dialect found on Google sites (requiring the `data-s` property)
- More info: https://2captcha.com/blog/update-google-recaptcha
Fixes #204
> feat(plugin-recaptcha): Support Google site specific recaptchas

- packages/puppeteer-extra-plugin-stealth/package.json
> Add dependency on stealth

- packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js
As per @jeroenvisser101's request
> chore: Fix link to Chromium code

- packages/puppeteer-extra-plugin-stealth/evasions/_utils/index.js
- packages/puppeteer-extra-plugin-stealth/evasions/_utils/index.test.js
- packages/puppeteer-extra-plugin-stealth/evasions/navigator.languages/index.test.js
- packages/puppeteer-extra-plugin-stealth/evasions/navigator.plugins/index.test.js
- packages/puppeteer-extra-plugin-stealth/evasions/navigator.vendor/index.test.js
- packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.test.js
This PR:
- improves error stack traces of our nested proxies
> fix(plugin-stealth): Improve toString stack traces

- packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha-api.ts
> fix(plugin-recaptcha): Add missing error handler in 2captcha api

- packages/puppeteer-extra-plugin-stealth/evasions/navigator.webdriver/index.js
- packages/puppeteer-extra-plugin-stealth/evasions/navigator.webdriver/index.test.js
- packages/puppeteer-extra-plugin-stealth/test/cat-and-mouse.test.js
- packages/puppeteer-extra-plugin-stealth/test/fpscanner.test.js
- packages/puppeteer-extra-plugin-stealth/test/util.js
> feat(plugin-stealth): Enhance the navigator.webdriver evasion for Chrome 89.0.4339

- packages/puppeteer-extra-plugin-user-data-dir/package.json
- yarn.lock
See: https://github.com/berstend/puppeteer-extra/issues/421#issuecomment-782600862
> chore: Upgrade fs-extra, possible fix for #421

- packages/puppeteer-extra-plugin-recaptcha/src/content-hcaptcha.ts
Fix berstend/puppeteer-extra#472
> fix(plugin-recaptcha): Update hCaptcha Detection

- packages/puppeteer-extra-plugin-stealth/evasions/webgl.vendor/index.js
- packages/puppeteer-extra-plugin-stealth/evasions/webgl.vendor/index.test.js
This PR hardens the webgl prototypes (fixes e.g. nike)
> fix(plugin-stealth): Harden webgl prototypes

- packages/puppeteer-extra-plugin-recaptcha/readme.md
- packages/puppeteer-extra-plugin-recaptcha/src/content.ts
- packages/puppeteer-extra-plugin-recaptcha/src/detection.test.ts
- packages/puppeteer-extra-plugin-recaptcha/src/index.ts
- packages/puppeteer-extra-plugin-recaptcha/src/solve.test.ts
- packages/puppeteer-extra-plugin-recaptcha/src/types.ts
Big overhaul and various improvements of the recaptcha plugin:
- More robust recaptcha detection and error handling
- Much better handling of multiple captchas on a page
- Better distinction of the various captcha types (checkbox, invisible, score)
- A boat load of additional tests for various captcha types
- Much improved debug logging: Added debug logging to the content script
- Additional plugin options to fine-tune advanced behavior
- Improved documentation & troubleshooting tips
I used my [growing suite of captcha demos](https://github.com/berstend/berstend.github.io/blob/main/static/recaptcha/) to methodically test against all the different captcha types/configs 😄
Fixes #489 
Most likely fixes #406
> feat(plugin-recaptcha): Improve overall detection & functionality

- .github/workflows/test.yml
- packages/playwright-extra/package.json
- packages/playwright-extra/src/helper/loader.ts
- packages/plugin-proxy-router/package.json
- packages/plugin-proxy-router/readme.md
- packages/plugin-proxy-router/rollup.config.ts
- packages/plugin-proxy-router/src/index.ts
- packages/plugin-proxy-router/src/plugin.ts
- packages/plugin-proxy-router/src/router.ts
- packages/plugin-proxy-router/src/stats.ts
- packages/plugin-proxy-router/src/utils/port.ts
- packages/plugin-proxy-router/tsconfig.json
- packages/plugin-proxy-router/tslint.json
- packages/puppeteer-extra-plugin-adblocker/package.json
- packages/puppeteer-extra-plugin-stealth/evasions/chrome.runtime/index.test.js
- packages/puppeteer-extra-plugin-stealth/evasions/webgl.vendor/index.test.js
- yarn.lock
> feat: Add plugin proxy-router

- packages/puppeteer-extra-plugin-recaptcha/src/content-hcaptcha.ts
- packages/puppeteer-extra-plugin-recaptcha/src/index.test.ts
- packages/puppeteer-extra-plugin-recaptcha/src/solve.test.ts
newassets.hcaptcha.com added to base url
> fix(plugin-recaptcha): Solve hcaptcha on newassets.hcaptcha.com
