berstend/puppeteer-extra

packages/puppeteer-extra-plugin-anonymize-ua/test/popup.js, packages/puppeteer-extra-plugin-anonymize-ua/test/stresstest.js, packages/puppeteer-extra-plugin/index.js, packages/puppeteer-extra-plugin/readme.md, packages/puppeteer-extra/index.js
Note: This patch only fixes explicitly created pages, implicitly created ones
(e.g. through `window.open`) are still subject to this issue. I didn't find a
reliable mitigation for implicitly created pages yet.
=> Patch targetcreated events (fixes #6)

packages/puppeteer-extra/index.js, yarn.lock
After refactoring starting in `puppeteer@1.8.0` the call signature changed in `lib/Puppeteer.js`:
https://github.com/GoogleChrome/puppeteer/pull/3208
This PR simplifies the puppeteer import and fixes this issue (and makes it less likely to break again in the future).
=> Simplify puppeteer import, fixes #17

packages/puppeteer-extra-plugin-adblocker/package.json, packages/puppeteer-extra-plugin-adblocker/readme.md, packages/puppeteer-extra-plugin-adblocker/rollup.config.ts, packages/puppeteer-extra-plugin-adblocker/src/index.test.ts, packages/puppeteer-extra-plugin-adblocker/src/index.ts, packages/puppeteer-extra-plugin-adblocker/src/types.ts, packages/puppeteer-extra-plugin-adblocker/tsconfig.json, packages/puppeteer-extra-plugin-adblocker/tslint.json, yarn.lock
Hi,
I am the maintainer of [`@cliqz/adblocker-puppeteer`](https://www.npmjs.com/package/@cliqz/adblocker-puppeteer) which allows to block ads and trackers in any puppeteer project. I thought this would be a nice addition to your collection of plugins!
I created a small POC by copying the recaptcha plugin and adapting it for the adblocker plugin. It allows to either block only ads (default) or trackers as well. There is an option which allows to cache the adblocker on disk to avoid having to perform network requests every time it is initialized.
Best,
Rémi
=> Add puppeteer-extra-plugin-adblocker

packages/puppeteer-extra-plugin/src/index.test.ts, packages/puppeteer-extra-plugin/src/index.ts
Hello,
If the defaults are not defined (or defined as an empty object) in a plugin, user options are ignored.
I've fixed the issue (+ added test to confirm).
Thanks!
=> Keep user options when defaults are not defined

packages/puppeteer-extra-plugin-stealth/evasions/user-agent-language-platform/index.js, packages/puppeteer-extra-plugin-stealth/evasions/user-agent-language-platform/index.test.js, packages/puppeteer-extra-plugin-stealth/evasions/user-agent-language-platform/package.json
This plugin basically replaces the following evasions:
https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth/evasions/accept-language
https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth/evasions/navigator.languages
At the same time, it fixes https://github.com/berstend/puppeteer-extra/issues/91
Instead of changing request headers and the ``navigator.languages`` (``navigator.language`` was missing by the way) properties as in the evasions above, we use call ``setUserAgentOverride`` in the CDP Network domain directly which is a better way of achieving this.
In addition, this evasion allows setting the ``navigator.platform`` and ``navigator.vendor`` properties, which makes it a lot less easy to detect …
=> feat(plugin-stealth): Add new user-agent-language-platform plugin

packages/puppeteer-extra-plugin-stealth/evasions/navigator.webdriver/index.js
This fixes function calls on the navigator object, for example ``navigator.javaEnabled()`` which is called by Google Analytics.
Related Chromium bug: https://bugs.chromium.org/p/v8/issues/detail?id=5773
=> Fix for calling functions on proxy (navigator.webdriver evasion)

packages/puppeteer-extra-plugin-devtools/lib/RemoteDevTools.js, packages/puppeteer-extra-plugin-devtools/package.json, packages/puppeteer-extra-plugin-devtools/readme.md, packages/puppeteer-extra-plugin-devtools/test/headless.js, yarn.lock
Allow [localtunnel options](https://github.com/localtunnel/localtunnel#options).
Provides workaround for #116 by specifying:
```js
localtunnel: {
host: 'https://tunnel.datahub.at'
}
```
or via insecure http:
```js
localtunnel: {
host: 'http://localtunnel.me'
}
```
=> Allow localtunnel options

packages/puppeteer-extra-plugin-stealth/index.js
New versions of puppeteer do not longer support the method setMaxListeners, and it makes puppeteer-extra-stealth not usable. 
This PR check if the method available before running it.
-----
Related Issue: https://github.com/berstend/puppeteer-extra/issues/228
=> Fixing issue with the setMaxListeners

package.json, yarn.lock
Therefore it may be processed properly when there's `--ignore-optional` (thanks to yarnpkg/yarn#7273).
Saves GNU/Linux users from the incompatible platform issue during installation.
Also regenerated `yarn.lock` after the change.
=> fix: Adding explicit declaration of fsevents as an optional dependency in package.json

packages/puppeteer-extra-plugin-recaptcha/src/index.ts
Some sites use `https://www.recaptcha.net/recaptcha/api.js` instead of `https://www.google.com/recaptcha/api.js` (e.g. [Mintos](https://www.mintos.com/en/login)).
=> Support script tag detection for different domains

packages/puppeteer-extra-plugin-stealth/evasions/navigator.plugins/index.js, packages/puppeteer-extra-plugin-stealth/evasions/navigator.plugins/index.test.js
Alright, this is the last one of those 😅 
With that our `navigator` props are peachy clean and this will return an empty array when using stealth:
```js
Object.getOwnPropertyNames(navigator)
// ==> []
```
=> fix(plugin-stealth): Harden navigator.plugins evasion

packages/puppeteer-extra/src/index.ts
This pull request addresses an issue where calling `puppeteer.launch()` without passing any options would trigger an error.
Closes: #223 #195 
Signed-off-by: Bruno Gaspar <brunofgaspar1@gmail.com>
=> Empty launch options

packages/extract-stealth-evasions/.gitignore, packages/extract-stealth-evasions/index.js, packages/extract-stealth-evasions/package.json, packages/extract-stealth-evasions/readme.md
This is a simple script to extract the stealth evasions to a minified JS file that can be used in browsers/non-puppeteer environments.
=> Add package: extract-stealth-evasions

packages/puppeteer-extra-plugin-recaptcha/src/content.ts
This PR fixes #300 
Captchas with 'invisible' in the src can be shown via js, at which point the plugin fails to find them.
My patch uses something equivalent to jquery's `is(':visible')` to check whether the captcha is visible to the user, rather than relying on the src value.
=> feat(plugin-recaptcha): Improve invisible iframe support

packages/puppeteer-extra-plugin-stealth/evasions/navigator.plugins/index.js, packages/puppeteer-extra-plugin-stealth/evasions/navigator.plugins/magicArray.js, packages/puppeteer-extra-plugin-stealth/evasions/navigator.plugins/mimeTypes.test.js, packages/puppeteer-extra-plugin-stealth/evasions/navigator.plugins/plugins.test.js, packages/puppeteer-extra-plugin-stealth/readme.md
This PR is based on #312 by @Niek and fixes/improves various issues with the `navigator.plugins` and `navigator.mimetypes` evasion.
This abomination is also now possible 😄 
```js
navigator.mimeTypes['application/pdf'].enabledPlugin[0].enabledPlugin[0]
.enabledPlugin[0].enabledPlugin[0].enabledPlugin[0].enabledPlugin[0].suffixes
// => pdf
```
=> fix(plugin-stealth): Improve navigator.plugin evasion

packages/puppeteer-extra-plugin-stealth/evasions/navigator.webdriver/index.js
To test, run:
```
PUPPETEER_EXECUTABLE_PATH=/path/to/chrome-unstable yarn run test
```
=> feat(plugin-stealth): Add webdriver fix for Chrome >= 88.0.4291.0

packages/puppeteer-extra-plugin-recaptcha/src/content.ts
All credits of this PR goes to @nsourov.
Currently, the plugin does not close the recaptcha window after solving it. I guess that in most cases the behavior is fine.
In my situation, the recaptcha window is opening on top of a button that I need to click, and what happens is that Puppeteer clicks the mouse at the position of the button, but since the recaptcha window is open, it clicks the recaptcha window and not the desired button.
This PR simply closes the recaptcha after solving it correctly.
=> feat(plugin-recaptcha): Hide captcha window after solving

.gitignore, packages/puppeteer-extra-plugin-recaptcha/src/content.ts, packages/puppeteer-extra-plugin-recaptcha/src/index.test.ts
This PR:
- adds improved support for detecting (and solving) invisible reCAPTCHAs, especially if the challenge is programmatically invoked
- In addition to looking for visible reCAPTCHA iframes we're now looking for invisible ones as well, but filter them by checking if there's an active challenge window open for them (otherwise we would get false positives and duplicates)
- adds an additional test making sure the plugin doesn't throw in case no captchas are found
Reference:
https://developers.google.com/recaptcha/docs/invisible#programmatic_execute
Potentially fixes #162
=> feat(plugin-recaptcha): Improve support for invisible reCAPTCHAs

packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha-api.ts
When http.request failed with ECONNRESET or similar it throw error instead of sending it to response.error
=> feat(plugin-recaptcha): Handle connection errors when solving

packages/puppeteer-extra-plugin-adblocker/package.json
Page object being Memory Leaked inside PuppeteerExtraPluginAdblocker
Issue: https://github.com/cliqz-oss/adblocker/issues/1449#issuecomment-730234360
Fixes https://github.com/berstend/puppeteer-extra/issues/375
=> Updated @cliqz/adblocker-puppeteer to 1.18.6 fix Memory leak

packages/puppeteer-extra-plugin-recaptcha/package.json, packages/puppeteer-extra-plugin-recaptcha/readme.md, packages/puppeteer-extra-plugin-recaptcha/src/content-hcaptcha.ts, packages/puppeteer-extra-plugin-recaptcha/src/content.ts, packages/puppeteer-extra-plugin-recaptcha/src/index.test.ts, packages/puppeteer-extra-plugin-recaptcha/src/index.ts, packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha-api.ts, packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha.ts, packages/puppeteer-extra-plugin-recaptcha/src/solve.test.ts, packages/puppeteer-extra-plugin-recaptcha/src/types.ts
I opted to re-use the same plugin name and APIs for convenience 😄 The term "reCAPTCHA" is now used in the same way `youtube-dl` supports much more than just youtube.
`page.solveRecaptchas()` will now solve any number and combination of: reCAPTCHA v2, reCAPTCHA v3, invisible reCAPTCHA, hCaptcha, invisible hCaptcha
Fixes #177
=> feat(plugin-recaptcha): Add support for hCaptcha

packages/puppeteer-extra-plugin-user-data-dir/index.js
Without the change, `fse.removeSync` only works with empty folder, so fails with ENOTEMPTY - https://github.com/jprichardson/node-fs-extra/issues/178
=> fix(plugin-user-data-dir): Prevent ENOTEMPTY error

packages/puppeteer-extra-plugin-stealth/evasions/_utils/index.js, packages/puppeteer-extra-plugin-stealth/evasions/_utils/index.test.js, packages/puppeteer-extra-plugin-stealth/evasions/_utils/withUtils.js, packages/puppeteer-extra-plugin-stealth/evasions/navigator.hardwareConcurrency/index.js, packages/puppeteer-extra-plugin-stealth/evasions/navigator.hardwareConcurrency/index.test.js, packages/puppeteer-extra-plugin-stealth/evasions/navigator.languages/index.js, packages/puppeteer-extra-plugin-stealth/evasions/navigator.languages/index.test.js, packages/puppeteer-extra-plugin-stealth/evasions/navigator.vendor/index.js, packages/puppeteer-extra-plugin-stealth/evasions/navigator.vendor/index.test.js, packages/puppeteer-extra-plugin-stealth/package.json
This PR:
- Hardens a couple of navigator evasions (`navigator.vendor`, `navigator.languages`, `navigator.hardwareConcurrency`) and patches leaks, with additional tests
- Adds re-usable stealth utilities for getter patching
- Cleans up stealth utilities a bit (e.g. we run `preloadCache` only once now)
- Fixes `Function.prototype.toString` error stack trace leaks
=> fix(plugin-stealth): Improve navigator patching

packages/puppeteer-extra-plugin-recaptcha/src/content.ts
Hi,
Thanks for maintain library.
While using puppeteer-extra-plugin-recaptcha, I found another set of urls for reCAPTCHA enterprise.
I added urls to recaptcha find method.
If you can, could you merge that?
I don't know enough your community rules, tell me what should I do if wrong.
thanks.
=> feat(plugin-recaptcha): Add support for reCAPTCHA Enterprise Add reCAPTCHA Enterprise support

packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js, packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.test.js, packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/readme.md
This PR adds support for UA hints to the `user-agent-override` evasion. Note that this is a breaking change, I opted to change the functionality of the evasion a bit and detect the platform (as well as the now required version, model, architecture, etc) all from the provided user agent string.
Unfortunately UA hints only work in headful (yet another reason not to use headless...), so the test needs to run in headful.
=> feat(plugin-stealth): Add support for UA hints

packages/puppeteer-extra-plugin-stealth/evasions/navigator.webdriver/index.js
This probably never affected any users, but the appending of `AutomationControlled` to existing flag would not work, because `e += ',AutomationControlled'` does not actually update the value in the `args` array, only the `e` variable inside the callback.
```js
const a = ['x','y','z'];
a.forEach(c => { c+= 'foo' } );
console.log(a) // ['x','y','z']
```
I also assume the `return` on line 33 was there to break out of the loop early, but again, it doesn't do anything.
This PR fixes it by inserting a new string into the array at the original index.
=> fix(plugin-stealth): Fix AutomationControlled flag override

.github/workflows/test.yml
* Change NodeJS 14 to 15
* Change Puppeteer 5.0.0 to 7.0.0
=> chore(ci): Bump NodeJS to v15 and puppeteer to v7

packages/puppeteer-extra-plugin-stealth/evasions/navigator.permissions/index.js, packages/puppeteer-extra-plugin-stealth/evasions/navigator.permissions/index.test.js
This PR:
- fixes the `navigator.permissions` evasion
The evasion has been weird/broken from the start, which is due to buggy behavior in vanilla headless (+ different behavior on secure/insecure origins). 
This PR adds a bunch of tests and fixes the evasion so headless will behave like headful.
=> feat(plugin-stealth): Rewrite navigator.permissions evasion

packages/puppeteer-extra-plugin-recaptcha/src/content.ts
…a.net
The goal of this PR is to add support for the recaptcha plugin to also solve recaptchas served from the `recaptcha.net` domain when `google.com` is unavailable. 
This PR should not introduce any breaking changes to the recaptcha handler itself. I was hesitant to generate docs in this PR as it generated docs for many other plugins in the repo. Please let me know if there is anything I can add!
For additional information, please see [recaptcha docs](https://developers.google.com/recaptcha/docs/faq) for further information
=> fix(plugin-recaptcha): Add recaptcha.net detection support

packages/puppeteer-extra-plugin-recaptcha/src/content.ts, packages/puppeteer-extra-plugin-recaptcha/src/detection.test.ts, packages/puppeteer-extra-plugin-recaptcha/src/index.ts, packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha.ts, packages/puppeteer-extra-plugin-recaptcha/src/solve.test.ts, packages/puppeteer-extra-plugin-recaptcha/src/types.ts
This PR is based on [previous discussions](https://github.com/berstend/puppeteer-extra/pull/400#issuecomment-823183394).
The main idea is to pass `enterprise=1` to 2captcha when an enterprise recaptcha is being detected. According to @divinedeveloper using the enterprise flag improved his success rate on hulu.com.
Unfortunately in my own testing (using my own [test sites](https://github.com/berstend/berstend.github.io/tree/main/static/recaptcha)) setting the enterprise flag made things worse (`ERROR_CAPTCHA_UNSOLVABLE`) so I'm keeping this opt-in for now, until we fully understood why this flag is not always improving the solving success rate.
In addition I added support for passing the optional `action` parameter (v3/enterprise) to 2captcha, this is opt-out as it didn't make a negative …
=> feat(plugin-recaptcha): Add useEnterpriseFlag and useActionValue options

packages/puppeteer-extra-plugin-recaptcha/src/content.ts, packages/puppeteer-extra-plugin-recaptcha/src/detection.test.ts, packages/puppeteer-extra-plugin-recaptcha/tsconfig.json
Based on [this discussion](https://github.com/berstend/puppeteer-extra/pull/482#issuecomment-826281337) and a follow up to #482.
At the end of the day there are more possible URLs for the recaptcha scripts to originate from (with/without www, using http or https, etc). 
This PR refactors the selector stuff to use a generator, which means we now support a grand total (and hopefully final) number of 16 recaptcha domains 😄
=> feat(plugin-recaptcha): Support more recaptcha domain combos

packages/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js
We recently started using [`enchant-puppeteer`](https://github.com/berstend/puppeteer-extra/issues/364#issuecomment-757049890) and doing our own asynchronous request interception while also using `puppeteer-extra-plugin-stealth`.  It seems like this combination makes it much more likely for this error to happen, especially on pages with redirects. The error was causing the whole process to be killed.
This seems relevant: https://github.com/puppeteer/puppeteer/issues/2258#issuecomment-380647459
We aren’t sure this is the right way to handle this problem. However, this seems like an improvement.
=> feat(plugin-stealth): Catch and mute certain Protocol errors

packages/puppeteer-extra-plugin-user-data-dir/index.js
puppeteer-extra-plugin-stealth
puppeteer-extra-plugin : user-agent-override
missing "onDisconnected" event will make application freeze
( Stuct in onClose event )
And can't use "onClose" because it's make freeze too
* **Deprecated:** Since puppeteer v1.6.0 `onDisconnected` has been improved
* and should be used instead of `onClose`.
*
* In puppeteer < v1.6.0 `onDisconnected` was not catching all exit scenarios.
also relate problem has mention it on other relate problem too
pluginStealth.enabledEvasions.delete('user-agent-override'); 
this short fix, but we need "user-agent-override" to work better than disable
I test fixed by this code
```
const express = require('express'); // Adding Express
const crypto = require('crypto');
const app = express(); // Initializing Express
var bodyParser = …
```
=> fix(plugin-user-data-dir): Use onDisconnect instead of onClose

packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.js, packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.test.js
I think I found how Cloudflare detects puppeteer: `iframe.contentWindow[0]` returns `undefined` in Chrome and returns `window` with puppeteer (and _iframe.contentWindow_ evasion). I modify `contentWindowProxy` to returns `undefined`.
Here is a case to see the difference between Chrome and puppeteer (with _iframe.contentWindow_ evasion).
```HTML
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
<script>
// https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.js
const contentWindowProxy = {
get(target, key) {
// Now to the interesting part:
// We actually make this thing behave like a regular iframe window,
// by intercepting calls to e.g. `.self` and redirect it to the correct thing. :)
// That …
```
=> fix(plugin-stealth): Improve iframe.contentWindow evasion

packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js, packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.test.js, packages/puppeteer-extra-plugin-stealth/package.json
This PR updates the regex used in the `user-agent-override` evasion to support generic Windows UAs (e.g. `Mozilla/5.0 (Windows NT 10.0)`).
It supersedes #554 by @jpxzp (no tests), and #440 by @nguyen930411 (PR got messed up with unrelated commits).
Fixes #553 #492
=> fix(plugin-stealth): Support generic windows UA in user-agent-override

packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.js, packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.test.js
Thanks to the good analysis in the issue https://github.com/berstend/puppeteer-extra/issues/543, I fixed an infinite recursion problem when calling `iframe.srcdoc` without assigning it a value.
=> fix(plugin-stealth): Improve iframe.srcdoc evasion

packages/puppeteer-extra-plugin-stealth/evasions/_utils/index.js
Fixes an inconsistency when an overridden getter is called via call or apply with more than zero arguments.
```js
const obj = { get foo() { return 1 } };
utils.replaceGetterWithProxy(obj, "foo", utils.makeHandler().getterValue(2));
console.log(obj.foo); // 2
console.log(Object.getOwnPropertyDescriptor(obj, "foo").get.call(obj, null)); // 1
```
Checking if `args` is truthy is redundant since it is guaranteed to be an array-like.
=> fix(plugin-stealth): Make makeHandler consistent with real getters

packages/puppeteer-extra-plugin-user-data-dir/index.js
`fs.rmdirSync` is deprecated since node >= v14.14.0, this PR supports using the new `fs.rmSync` when available (node >= v14.14.0)
Fixes #556
=> fix(plugin-user-data-dir): Use new fs.rmSync when available

packages/puppeteer-extra-plugin-devtools/package.json
This bumps the url-parse dependency.
=> deps(plugin-devtools): Bump url-parse from 1.4.0 to 1.5.3

packages/puppeteer-extra-plugin-user-data-dir/package.json
Update fs-extra to v10.0.0 to avoid deprecation warning on Node 16.x
=> deps(plugin-user-data-dir): Bump fs-extra to v10.0.0 to avoid DeprecationWarning

packages/puppeteer-extra-plugin-devtools/lib/RemoteDevTools.js, packages/puppeteer-extra-plugin-devtools/package.json, packages/puppeteer-extra-plugin-devtools/readme.md, packages/puppeteer-extra-plugin-devtools/test/headless.js, yarn.lock
The devtools index page ("Select target to inspect") differs between headful and headless browser instances, the latter now started to client-side modify the devtoolsFrontendUrl to something that breaks the [devtools plugin](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-devtools) functionality - this PR fixes this.
In addition we re-enable CI testing of the devtools plugin.
Thanks to @abowcut for reporting and investigating this issue, fixes #566, #249
=> fix(plugin-devtools): Support headless again by modifying index page

packages/puppeteer-extra-plugin-devtools/lib/RemoteDevTools.js
As mentioned on many [issues](https://github.com/localtunnel/localtunnel/issues/258) on the localtunnel [github](https://github.com/localtunnel/localtunnel), using the public localtunnel server leads to crashes quite frequently as the public server becomes overloaded many times throughout the day.
Currently, when using the devtools plugin, if the public localtunnel server is having one of its "episodes" and the connection refused error is thrown the entire node process that puppeteer is running in crashes.
This pull request simply adds a listener to the tunnel for the error event and handles it so that even though the cdp might not be working for that browser at least the node process can continue to run.
To me this is definitely preferable over having the whole node process running …
=> fix(plugin-devtools): Add localtunnel error event

packages/puppeteer-extra/readme.md
- Adds my plugin [puppeteer-extra-plugin-portal](https://github.com/claabs/puppeteer-extra-plugin-portal) to the community plugins section. I finally released it, so I figured I may as well add it to the list.
- Remove the puppeteer version notice for types now that #428 is closed
=> docs(puppeteer-extra): Remove types notice, add community plugin

packages/puppeteer-extra-plugin-stealth/evasions/defaultArgs/index.test.js, packages/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js, packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js
It's just an example. I'm sure it could be nicer, but it works (at least for me; I couldn't run the tests because of Windows and there comes the error "Failed to download Firefox rv0.0.1!"). No time to fix this error.
**Edit:** 
The problem is that `puppeteer@14` has finally made '#client' private. However, there is still/or now the function `Page._client()`, which returns the client. To avoid problems between `<@14` and `>=@14`, I made it a bit "uglier".
**Edit (2):**
I had to make a 2nd commit because for some reason the 1st push didn't push the changes to the defaultArg test(s). (And another one to remove the dummy blank spaces.)
=> fix(plugin-stealth): Support puppeteer 14 private cdp client

packages/puppeteer-extra-plugin-recaptcha/src/content-hcaptcha.ts
The query selector from the method `_findActiveChallenges` changed, so I updated it.
However, I didn't find a good way to test this, because the `test('will detect hCAPTCHAs')` uses [this url](http://democaptcha.com/demo-form-eng/hcaptcha.html) and it is tested by the method `_findRegularCheckboxes`.
=> fix(plugin-recaptcha): Update hcaptcha challenge query selector

packages/puppeteer-extra-plugin-recaptcha/src/index.ts
I encountered a different syntax today for a hcaptcha js script on a Cloudflare page:
```
https://cloudflare.hcaptcha.com/1/api.js?endpoint=https%3A%2F%2Fcloudflare.hcaptcha.com&assethost=https%3A%2F%2Fcf-assets.hcaptcha.com&imghost=https%3A%2F%2Fcf-imgs.hcaptcha.com&render=explicit&recaptchacompat=off&onload=_cf_chl_hload
```
This url will not be recognized by the previous pattern since that one expected `//hcaptcha`, so i changed it to allow subdomains.
=> fix(plugin-recaptcha): Change `hcaptcha.com` script recognition url

packages/puppeteer-extra-plugin-stealth/readme.md
Remove an extra `e` in `puppeeteer-extra`.
=> docs: Fix readme typo

packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha-api.ts
https://2captcha.com/2captcha-api#solving_captchas
They say "Our API is based on HTTP requests and supports both HTTP and HTTPS protocols."
I did a find and replace to change "http" to "https" and made a few small changes. I ran the tests for the puppeteer-extra-plugin-recaptcha and they passed.
=> feat(plugin-recaptcha): Use https for the 2captcha captcha solving API

packages/puppeteer-extra-plugin-adblocker/package.json, packages/puppeteer-extra-plugin-adblocker/readme.md, packages/puppeteer-extra-plugin-adblocker/src/index.ts, packages/puppeteer-extra-plugin-block-resources/example.js, packages/puppeteer-extra-plugin-block-resources/index.d.ts, packages/puppeteer-extra-plugin-block-resources/index.js, packages/puppeteer-extra-plugin-block-resources/index.test.js, packages/puppeteer-extra-plugin-block-resources/package.json, packages/puppeteer-extra-plugin-block-resources/readme.md, packages/puppeteer-extra/package.json, yarn.lock
Adds support for the new [Cooperative Intercept Mode available in Puppeteer v11+](https://github.com/puppeteer/puppeteer/blob/v11.0.0/docs/api.md#upgrading-to-cooperative-mode-for-package-maintainers) and defining a custom `interceptResolutionPriority` for the following plugins:
- `puppeteer-extra-plugin-block-resources`
- `puppeteer-extra-plugin-block-adblocker`
This change checks that the required interception functions are available, so it's backwards compatible with the Legacy Mode and previous Puppeteer versions.
The `@cliqz/adblocker-puppeteer` dependency [already included support for Cooperative Mode in v1.23.0](https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer/CHANGELOG.md#v1230-mon-oct-18-2021).
Fixes #364, #156
=> feat(plugin-adblocker): Add cooperative intercept mode support

packages/puppeteer-extra-plugin-recaptcha/readme.md, packages/puppeteer-extra-plugin-recaptcha/src/provider/2captcha.ts
This pull request adds support for using proxies in puppeteer-extra. The docs for 2captcha proxies is [here](https://2captcha.com/2captcha-api#proxies). 
To use proxies all you need to do is set two environment variables (``2CAPTCHA_PROXY_TYPE`` and ``2CAPTCHA_PROXY_ADDRESS``) and the program will add the extra options when sending the request to 2captcha.
This will help bypass detection.
@berstend
=> feat(plugin-recaptcha): Add proxy support

.github/workflows/test.yml, packages/playwright-extra/.prettierrc.js, packages/playwright-extra/package.json, packages/playwright-extra/readme.md, packages/playwright-extra/rollup.config.ts, packages/playwright-extra/src/extra.ts, packages/playwright-extra/src/helper/loader.ts, packages/playwright-extra/src/index.ts, packages/playwright-extra/src/plugins.ts, packages/playwright-extra/src/puppeteer-compatiblity-shim/index.ts, packages/playwright-extra/src/puppeteer-compatiblity-shim/playwright-shim.d.ts, packages/playwright-extra/src/types/index.ts, packages/playwright-extra/test/exports.spec.ts, packages/playwright-extra/test/fixtures/dummyplugin.ts, packages/playwright-extra/test/fixtures/extra.ts, packages/playwright-extra/test/playwright.config.ts, packages/playwright-extra/test/plugin-events.spec.ts, packages/playwright-extra/test/puppeteer-plugins/anonymize-ua.spec.ts, packages/playwright-extra/test/puppeteer-plugins/recaptcha.spec.ts, packages/playwright-extra/test/puppeteer-plugins/stealth.spec.ts, packages/playwright-extra/tsconfig.json, yarn.lock
This PR:
- adds a new `playwright-extra` package
- it features a puppeteer compatibility layer so existing plugins derived from `PuppeteerExtraPlugin` (and expecting certain puppeteer methods) can be used with it
- currently tested and optimized for the stealth (chromium) and recaptcha (chromium, firefox, webkit) plugin
This approach is much more sane as opposed to switching everything to a new shared plugin base class at once, as attempted in #303 
Further background on the reasoning behind this strategy change can be found here: https://github.com/berstend/puppeteer-extra/issues/454#issuecomment-1169678855
The code (informed by maintaining a plugin framework for 4 years now 😄) is in parts much more elegant than puppeteer-extra and once some overdue housekeeping in the repo has been done …
=> feat: Add playwright-extra

packages/puppeteer-extra-plugin-recaptcha/src/playwright-mods.d.ts, packages/puppeteer-extra-plugin-recaptcha/src/types.ts
This allows e.g. `await page.solveRecaptchas()` to be used with type support when playwright-extra is driving the plugin (#664)
=> feat(plugin-recaptcha): Add playwright type mods

packages/puppeteer-extra/package.json, packages/puppeteer-extra/readme.md, packages/puppeteer-extra/src/index.ts, packages/puppeteer-extra/test/addExtra.ts
- Remove deprecated `puppeteer-firefox`
- Fixes: #623, #512
=> chore(puppeteer-extra): Remove deprecated `puppeteer-firefox`

packages/puppeteer-extra-plugin-adblocker/src/index.ts
The new `blockTrackersAndAnnoyances` option now configures whether annoyances are also blocked.
I kept the old option to maintain backwards compatibility.
=> feat(plugin-adblocker): Add option for fromPrebuiltFull

packages/puppeteer-extra-plugin-recaptcha/src/index.ts
This one was a real pain in the *@#^@.
But now the sun can shine once again, and the scraping can continue!
Basically, was having a blast running `plugin-recaptcha` locally with `ts-node`, and once the same code hit production aws lambdas it started throwing the mentioned error.
Long story short, it was `esbuild` and the way it transformed `RecaptchaContentScript` & `HcaptchaContentScript` classes into something like `var HcaptchaContentScript = class {`.
The fix looks for such a sequence and injects the class name back.
=> fix(plugin-recaptcha): Support esbuild transpilation of content scripts

packages/puppeteer-extra-plugin-recaptcha/src/content-hcaptcha.ts, packages/puppeteer-extra-plugin-recaptcha/src/content.ts, packages/puppeteer-extra-plugin-recaptcha/src/index.ts
This PR builds on https://github.com/berstend/puppeteer-extra/pull/758
It also fixes a fix to workaround `esbuild`'s `__name` semantics: https://github.com/esbuild-kit/tsx/issues/113
The author of `esbuild` [recommends](https://github.com/evanw/esbuild/issues/1031) against calling `toString()` on a function or class as this library is doing and instead creating a separate build for these entrypoints. This results in a lot more deterministic functionality, but that would also involve a larger PR.
So for now, this is the minimal amount of code changes to get `puppeteer-extra-plugin-recaptcha`'s injected content scripts to work when used in an application that's compiled using `esbuild`.
I ran into this issue while building the [chatgpt node.js …
=> fix(plugin-recaptcha): Enhance esbuild transpilation support of content scripts

packages/puppeteer-extra/src/index.ts
puppeteer started to depend on puppeteer-core since probably [v18.1.0](https://github.com/puppeteer/puppeteer/blob/bafdb4784ccfe4a35fec9e6d366e4d1b40a82e1b/packages/puppeteer/package.json), but there are some API limitations on puppeteer core, like `puppeeter.defaultDownloadPath()`
=> fix(puppeteer-extra): Prefer puppeteer over puppeteer-core
